### ISSUE TITLE
US flag is set to unknown.png while there is a US flag in the assets

### ISSUE THREAD

**Issue by silverhairs** [NovelCOVID/API#163]

**Comment by ebwinters** [comment]
@buster95 this is why I was talking about standardizing names. For a fix, you would need to make sure that `countryData` in the file `/utils/country_utils` has all the correct standardized country names according to `countryMap.js`. For example
```javascript
{ country: "United Kingdom", iso2: "GB", iso3: "GBR", _id: 826, lat: 54, long: -2 },
// needs to become ...
{ country: "UK", iso2: "GB", iso3: "GBR", _id: 826, lat: 54, long: -2 },
```
because UK is the standardized name, and therefore right now, `getCountryData` is broken.

**Comment by buster95** [comment]
@ebwinters was resolve on my last PR #117, I'm waiting for merge
