### ISSUE TITLE
No recovered data

### ISSUE THREAD

**Issue by Abdulqudus001** [NovelCOVID/API#196]
Data for people who have recovered has been removed from version 2

**Comment by ebwinters** [comment]
this issue gets posted at least 3 times a day lol, check the README and check closed issues.

**Comment by dicedtomatoreal** [comment]
Because JHU has removed it

**Comment by dicedtomatoreal** [comment]
beat me to it.. :joy:

**Comment by Krato** [comment]
Sorry to write again in a closed issue @dicedtomatoreal But I think that they restore again the recovery data.

Please check it here: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

**Comment by ebwinters** [comment]
I was trying to fix this, but it might have to get put off until John's Hopkins gets it together. The data in the CSV file @Krato linked has length less than the other two CSV files we pull fro, which causes inconsistencies in the data. I think it is best to add this feature once JHU fixes their data source so that we don't have to go back and change our CSV parsing logic when they do finally fix the data inconsistency

**Comment by ebwinters** [comment]
Upon further inspection, recovered data is only missing all canadian provinces. I can make a PR to add recovered data for all but canadian provinces. 👍
