### ISSUE TITLE
[Feature Request] API calls for city/county level data

### ISSUE THREAD

**Issue by prabhathc** [NovelCOVID/API#289]
I see that [time series data](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series), which doesn't have city/county level data, is currently being used to back this API. In order to make retrieving more specific data possible, one could use [daily reports](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/03-28-2020.csv) to update a local data source formatted in accordance to current requirements. This would initially require backfilling all the daily reports and ensuring there are no discrepancies between the new data source and the time series data (which shouldn't occur because the the time series data should rely on daily reports). If this feature is added, this API can be used for cases that require specific data. Also, this issue is similar to #56, #285 and #5, which shows people want this feature.

**Comment by S1MB10T3** [comment]
I'm personally working on getting nyc data for my own project. I can make a PR when that's done but it will be only nyc though.

Not sure we're to get aggregate data of multiple cities without compiling a list yourself.

**Comment by ebwinters** [comment]
We don't need a PR for one city data. We are discussing among owners how we will go about this

**Comment by ritik07** [comment]
Can we get data like stats of every state of the respective country?

**Comment by EliteDaMyth** [comment]
@ritik07 we need good sources for it.

**Comment by acxz** [comment]
I believe what @prabhathc linked in the OP is a good data source no? The daily reports, example [here](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/03-28-2020.csv) contain state/county (or 1 administration smaller) data for some countries (where data is available of course). In fact this is the exact data that the JHU map uses.

I'm also a bit confused, based on the labels I had thought this feature would eventually be implemented, but since it has been closed, is this not the case anymore?

**Comment by ebwinters** [comment]
I'll be looking into this today, and hopefully starting a US counties feature
![](https://i.giphy.com/media/1jajO78uBuN8MkxNa4/giphy.gif)

**Comment by ritik07** [comment]
Get it from https://www.covid19india.org/
