### ISSUE TITLE
some countries shown as provinces in history data

### ISSUE THREAD

**Issue by MarkSmit** [NovelCOVID/API#350]
Some countries are displayed as provinces of a country.
For example, Aruba, Curaçao and Sint Maarten are countries within the kingdom of the Netherlands, but they are displayed as a province of the Netherlands. The numbers of those three countries are also added to the main country info. When you request `/v2/historical/NL` you get the numbers of the country the Netherlands plus the numbers of Aruba, Curaçao and Sint Maarten, which should be separated. https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv shows a separate row for the country, but that one can't be accessed via the api right now, only the one with all the countries added together.

**Comment by MarkSmit** [comment]
These countries also can't be accessed by their ISO2.
For example:
- `/v2/historical/AW` doesn't work (`/v2/historical/NL/AW` neither)
- `/v2/historical/CW` doesn't work (`/v2/historical/NL/CW` neither)
- `/v2/historical/SX` doesn't work (`/v2/historical/NL/SX` neither)

**Comment by ebwinters** [comment]
I'll fix it today

**Comment by ebwinters** [comment]
This endpoint works by summing all provinces the country respective country, in this case, the netherlands. The reason `/v2/historical/AW` won't work is because it is a province, not a country. If you want specific data for the provinces within a country, you would use `https://corona.lmao.ninja/v2/historical/nl/aruba`, an you would get the provinces within a country from the `provinces` field returned in`https://corona.lmao.ninja/v2/historical/nl`

**Comment by ebwinters** [comment]
What i can do is enter a province in each called "mainland", which would be data on the mainland for the country excluding separate provinces. The reason why the data is formatted this way is because countries like china and canada don't have a mainland entry, and instead need to be summed over all their provinces.

**Comment by MarkSmit** [comment]
Can the iso2 codes be used then? Will the mainland be accessible via `/v2/historical/NL/NL`?

**Comment by ebwinters** [comment]
you access provinces by their full name, which you get from the `provinces` field returned with the historical data. It will be accessed by `/v2/historical/NL/mainland` once I make the PR
