### ISSUE TITLE
Canada recovered historical data is missing.

### ISSUE THREAD

**Issue by Makzoite** [NovelCOVID/API#420]
Canada recovered historical data is all 0.

**Comment by ebwinters** [comment]
This has to do with how we read the recovered file. JHU csv files for cases and deaths do not have a canada row, they only have rows for each Canadian province. The data does not match up and we cannot really do much about it. I can try to make a manual fix for Canada since that is the only country this happens with.

**Comment by ebwinters** [comment]
on second thought it's too much work, will wait for JHU to fix on backend
![](https://media3.giphy.com/media/bqalUGFYfyHzW/giphy.gif?cid=ecf05e4720e3a085f61094c6555554e92a7a96434d32bcdd&rid=giphy.gif)
