### ISSUE TITLE
Map v1 endpoint to v2

### ISSUE THREAD

**Issue by colbyfayock** [NovelCOVID/API#528]
Is there any chance you all would be willing to maintain the v1 endpoints by redirecting them to v2? In my case, particularly /countries, but if you can map https://corona.lmao.ninja/ > https://corona.lmao.ninja/v2, it would be helpful.

My request is small compared to what you all are doing with this, but I had a fair amount of people work through a tutorial with that endpoint, and I'm guessing all their solutions are broken now. Luckily I can update the written parts, but I'm guessing it will leave most of them stuck wondering what's going on.

Tutorial:
https://www.youtube.com/watch?v=GryBIsfBfro
https://www.freecodecamp.org/news/how-to-create-a-coronavirus-covid-19-dashboard-map-app-in-react-with-gatsby-and-leaflet/

Thanks

**Comment by ebwinters** [comment]
Really cool to see a tutorial using our API 🤠

Actually. A lot of people have asked to do this and I’ve said no because of different data structures. But it is possible to do it for the endpoints we deprecated today and give people slightly more time to adjust, even though this was announced **a week ago**. We are trying to retire v1 of the api, and it’s hard to do that if it is still usable. 
Let me think it over for a bit

**Comment by colbyfayock** [comment]
Totally understand if not, my fault for not having kept up with the updates. Figured I'd ask though! Thanks either way.

**Comment by puf17640** [comment]
@colbyfayock i understand you but it would be bad practice to map old endpoints to new ones instead of only supporting the new ones, since there is a reason the old ones were deprecated.

the reason for making a new version of endpoints is that the structure and the way you use the api changes so that it would break applications. 
we made an announcement that we are going to deprecate and added an issue to the repo also stating the deprecation. just to clarify we did not just deprecate them without notice haha, i also understand that you arent monitoring what we announce daily, i wouldnt do it too if i wasnt working on it, so i would suggest you join the discord channel so you get updates per push notification to api news.

**Comment by puf17640** [comment]
@colbyfayock can't you add an annotation to the video that tells people to use /v2/ endpoints? i havent uploaded a video to youtube yet

**Comment by colbyfayock** [comment]
@puf17640 totally understand your position :) no problem. biggest bummer though is people who have already created it and wont realize until they go back and see it broken

Fwiw i think the /countries endpoint is identical 🤷‍♂️ i only needed to update the endpoint

WRT the annotations - i think you have to have a certain number of subscribers before being able to do that, but will check and see if i can 🤔 good idea

**Comment by puf17640** [comment]
@colbyfayock yeah i feel that, some people will be quite confused :/

yeah /countries and /all endpoint are pretty much the same structure but work a bit different codewise, we wanted to update all endpoints to v2 and not just the ones that changed

crazy to think about it but i will have a discussion with ethan about it, maybe we could really redirect the endpoints that are "the same"

**Comment by colbyfayock** [comment]
yeah and again - totally understand if not. i appreciate you all considering it though!
