### ISSUE TITLE
Not getting Yesterday Data

### ISSUE THREAD

**Issue by akanshgulati** [NovelCOVID/API#532]
We are getting deprecated errors on API v1 and with v2, no yesterday data is coming
https://corona.lmao.ninja/v2/countries/IN?yesterday=true

**Comment by puf17640** [comment]
Well that might be because of the v1 endpoints being deprecated as of yesterday. 
What do you mean by no yesterday data is coming? Open the link and see yourself.

**Comment by akanshgulati** [comment]
Okay, I got it by setting the flag `yesterday` to true I am only getting yesterday data..I assumed that it will show me both today and yesterday data.

**Comment by akanshgulati** [comment]
@puf17640 This was handled in much better way with different API for yesterday. Setting a flag for yesterday seems like a add-on we are asking just like you offfer `sort` in flag.

**Comment by puf17640** [comment]
> @puf17640 This was handled in much better way with different API for yesterday. Setting a flag for yesterday seems like a add-on we are asking on the **same** data just like you offfer `sort` in flag.

well, I agree on that. the yesterday endpoint was better than ?yesterday but I can't really see a problem in that, just use `/v2/countries/COUNTRY?yesterday=true` instead of `/yesterday/COUNTRY`. 

if you are using javascript or python, you can also use the api wrappers and not worry about any changes to the api
